---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v6.8.0

inputs:
- name: bbl-state
- name: logsearch-boshrelease

run:
  path: logsearch-boshrelease/deployment/ci/tasks/smoke-tests.sh

params:
  BBL_STATE_DIR: bbl-state