releases:
- name: logsearch
  version: latest

jobs:
###############################################################################
#First deploy group - elasticsearch_master, cluster_monitor, maintenance
###############################################################################
- name: elasticsearch_master
  instances: 1
  templates:
  - { name: elasticsearch, release: logsearch, consumes: {elasticsearch: nil} }
  - { name: cerebro, release: logsearch, consumes: {elasticsearch: nil} }
  - { name: syslog_forwarder, release: logsearch, consumes: {syslog_forwarder: nil} }
  resource_pool: elasticsearch_master
  persistent_disk_pool: elasticsearch_master
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
  properties:
    elasticsearch:
      node:
        allow_master: true
        allow_data: false
    syslog_forwarder:
      config:
      - {service: elasticsearch, file: /var/vcap/sys/log/elasticsearch/elasticsearch.stdout.log}
      - {service: elasticsearch, file: /var/vcap/sys/log/elasticsearch/elasticsearch.stderr.log}
  update:
    max_in_flight: 1 # Should never update more than one ES master node at a time or cluster will go down

- name: cluster_monitor
  instances: 1
  templates:
  - { release: logsearch, name: ingestor_syslog }
  - { release: logsearch, name: elasticsearch, consumes: {elasticsearch: nil} }
  - { release: logsearch, name: elasticsearch_config, consumes: {elasticsearch: nil} }
  - { release: logsearch, name: curator, consumes: {elasticsearch: nil} }
  - { release: logsearch, name: kibana, consumes: {elasticsearch: nil} }
  - { release: logsearch, name: nats_to_syslog, consumes: {syslog_forwarder: nil} }
  resource_pool: cluster_monitor
  networks:
  - name: default
    static_ips: (( static_ips(2) ))
  persistent_disk_pool: cluster_monitor
  properties:
    kibana:
      port: 5601
      elasticsearch:
        host: 127.0.0.1
        port: 9200
      memory_limit: 30
      wait_for_templates: [shards-and-replicas]
    elasticsearch:
      master_hosts: [127.0.0.1]
      cluster_name: monitor
      node:
        allow_master: true
        allow_data: true
    redis:
      host: 127.0.0.1
      maxmemory: 10
    curator:
      elasticsearch:
        host: 127.0.0.1
        port: 9200
      purge_logs:
        retention_period: 7
    elasticsearch_config:
      elasticsearch:
        host: 127.0.0.1
        port: 9200
      index_prefix: "logstash-"
      templates:
        - shards-and-replicas: "{ \"template\" : \"logstash-*\", \"order\" : 100, \"settings\" : { \"number_of_shards\" : 1, \"number_of_replicas\" : 0 } }"
        - index-settings: /var/vcap/jobs/elasticsearch_config/index-templates/index-settings.json
        - index-mappings: /var/vcap/jobs/elasticsearch_config/index-templates/index-mappings.json
    logstash_parser:
      logstash_parser.elasticsearch.index: "logstash-%{+YYYY.MM.dd}"
      filters:
      - monitor: /var/vcap/packages/logsearch-config/logstash-filters-monitor.conf
    nats_to_syslog:
      debug: true
    logstash_ingestor:
      syslog:
        port: 5514

- name: maintenance
  instances: 1
  templates:
  - { name: elasticsearch_config, release: logsearch, consumes: {elasticsearch: nil} }
  - { name: curator, release: logsearch, consumes: {elasticsearch: nil} }
  - { name: syslog_forwarder, release: logsearch, consumes: {syslog_forwarder: nil} }
  resource_pool: maintenance
  networks:
  - name: default
  update:
    serial: true # Block on this job to create deploy group 1
  properties:
    syslog_forwarder:
      config:
      - {service: curator, file: /var/vcap/sys/log/curator/curator.log}
      - {service: elasticsearch_config, file: /var/vcap/sys/log/elasticsearch_config/job.control.log}

##################################################################
#2nd deploy group - elasticsearch_data, kibana, ingestors
##################################################################

- name: elasticsearch_data
  instances: 2
  templates:
  - { name: elasticsearch, release: logsearch, consumes: {elasticsearch: nil} }
  - { name: syslog_forwarder, release: logsearch, consumes: {syslog_forwarder: nil} }
  resource_pool: elasticsearch_data
  persistent_disk_pool: elasticsearch_data
  networks:
  - name: default
  properties:
    elasticsearch:
      node:
        allow_master: false
        allow_data: true
    syslog_forwarder:
      config:
      - {service: elasticsearch, file: /var/vcap/sys/log/elasticsearch/elasticsearch.stdout.log}
      - {service: elasticsearch, file: /var/vcap/sys/log/elasticsearch/elasticsearch.stderr.log}
  update:
    serial: true
    max_in_flight: 1 # Only update 1 ES data node at a time or risk downtime

- name: kibana
  instances: 1
  templates:
  - { name: kibana, release: logsearch, consumes: {elasticsearch: nil} }
  - { name: syslog_forwarder, release: logsearch, consumes: {syslog_forwarder: nil} }
  - { name: elasticsearch, release: logsearch, consumes: {elasticsearch: nil} }
  resource_pool: kibana
  networks:
  - name: default
    static_ips: (( static_ips(5) ))
  properties:
    syslog_forwarder:
      config:
      - {service: kibana, file: /var/vcap/sys/log/kibana/kibana.stdout.log}
      - {service: kibana, file: /var/vcap/sys/log/kibana/kibana.stderr.log}

- name: ingestor
  instances: 1
  templates:
  - { name: elasticsearch, release: logsearch, consumes: {elasticsearch: nil} }
  - { name: ingestor_syslog, release: logsearch }
  - { name: syslog_forwarder, release: logsearch, consumes: {syslog_forwarder: nil} }
  resource_pool: ingestor
  persistent_disk_pool: ingestor
  networks:
  - name: default
    static_ips: (( static_ips(1) ))
  properties:
    logstash_ingestor:
      debug: false
      relp:
        port: ~
    syslog_forwarder:
      config:
      - {service: elasticsearch, file: /var/vcap/sys/log/elasticsearch/elasticsearch.stdout.log}
      - {service: elasticsearch, file: /var/vcap/sys/log/elasticsearch/elasticsearch.stderr.log}
      - {service: ingestor_syslog, file: /var/vcap/sys/log/ingestor_syslog/ingestor_syslog.stdout.log}
      - {service: ingestor_syslog, file: /var/vcap/sys/log/ingestor_syslog/ingestor_syslog.stderr.log}

- name: ingestor-bosh-nats
  instances: 0
  templates:
  - { name: ingestor_syslog, release: logsearch }
  - { name: nats_to_syslog, release: logsearch, consumes: {syslog_forwarder: nil} }
  - { name: syslog_forwarder, release: logsearch, consumes: {syslog_forwarder: nil} }
  resource_pool: ingestor
  networks:
  - name: default
    static_ips: (( static_ips(4) ))
  properties:
    logstash_ingestor:
      syslog:
        port: 5514
    syslog_forwarder:
      config:
      - {service: nats_to_syslog, file: /var/vcap/sys/log/nats_to_syslog/nats_to_syslog.stdout.log}
      - {service: nats_to_syslog, file: /var/vcap/sys/log/nats_to_syslog/nats_to_syslog.stderr.log}

####################################################
#3rd deploy group - ls-router (haproxy), and errands
####################################################

- name: ls-router
  instances: 1
  templates:
  - { name: haproxy, release: logsearch, consumes: {elasticsearch: nil, syslog_forwarder: nil, kibana: nil, ingestor: nil} }
  resource_pool: haproxy
  networks:
  - name: default
    default: [gateway, dns]
    static_ips: (( static_ips(9) ))
  properties:
    haproxy:
      syslog_server: (( grab jobs.cluster_monitor.networks.[0].static_ips.[0] ))
      ingestor:
        backend_servers: (( grab jobs.ingestor.networks.[0].static_ips ))
      kibana:
        backend_servers: (( grab jobs.kibana.networks.[0].static_ips ))
      cluster_monitor:
        backend_servers: (( grab jobs.cluster_monitor.networks.[0].static_ips ))

- name: smoke-tests
  instances: 1
  resource_pool: errand
  release: logsearch
  templates:
  - { name: smoke-tests, release: logsearch , consumes: {elasticsearch: nil} }
  consumes: {elasticsearch: nil}
  networks:
  - name: default
  lifecycle: errand
  properties:
    smoke_tests:
      syslog_ingestor:
        host: (( grab jobs.ls-router.networks.[0].static_ips.[0] ))
        port: (( grab jobs.ls-router.properties.haproxy.ingestor.inbound_port || properties.haproxy.ingestor.inbound_port || 5514 ))
      elasticsearch_master:
        host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))

# Global properties
properties:
  curator:
    purge_logs:
      unit: days
      retention_period: 30
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
      port: 9200
  logstash_parser:
    debug: false
  logstash_ingestor:
    debug: false
  elasticsearch:
    master_hosts: (( grab jobs.elasticsearch_master.networks.default.static_ips ))
    cluster_name: logsearch
    exec: ~
  elasticsearch_config:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
    templates:
      - shards-and-replicas: /var/vcap/jobs/elasticsearch_config/index-templates/shards-and-replicas.json
      - index-settings: /var/vcap/jobs/elasticsearch_config/index-templates/index-settings.json
      - index-mappings: /var/vcap/jobs/elasticsearch_config/index-templates/index-mappings.json
  syslog_forwarder:
    host: (( grab jobs.cluster_monitor.networks.default.static_ips.[0] ))
    port: (( grab jobs.cluster_monitor.properties.logstash_ingestor.syslog.port ))
  nats_to_syslog:
    # NATS settings of the Bosh Director
    nats:
      subject: ">"
      user: nats
      password: nats-password
      port: 4222
      machines: [10.0.16.5]
    syslog:
        host: 127.0.0.1
        port: 5514
