---
name: logsearch
director_uuid: VAR_UUID # BOSH UUID

jobs:
- name: elasticsearch_master
  instances: 1

- name: elasticsearch_data
  instances: 2

- name: ingestor
  instances: 1

- name: ingestor-bosh-nats
  instances: 1

- name: queue
  instances: 1

- name: parser
  instances: 1

- name: kibana
  instances: 1

- name: maintenance
  instances: 1

- name: cluster_monitor
  instances: 1

properties:
  nats_to_syslog:
    # Specify the NATS settings of the Bosh Director
    nats:
      user: VAR_NATS_USER  # Specify NATS user
      password: VAR_NATS_PASS  # Specify NATS password
      port: 4222  # Default value
      machines: [VAR_NATS_IP]  # Specify your NATS IPs
