meta:
  availability_zone: nova
  instance_type:
    compilation: m1.medium
    elasticsearch: m1.medium
    queue: m1.small
    ingestor: m1.small
    parser: m1.small
    kibana: m1.small
    maintenance: m1.small
    monitor: m1.small
    haproxy: m1.small
    errand: m1.small
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest

releases:
- name: logsearch
  version: latest

name: logsearch
director_uuid: VAR_UUID # BOSH UUID

jobs:
# Deploy group 1
- name: elasticsearch_master
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
  resource_pool: elasticsearch_master
  persistent_disk_pool: elasticsearch_master

- name: cluster_monitor
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(2) ))
  resource_pool: cluster_monitor

- name: queue
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(3) ))
  resource_pool: queue
  persistent_disk_pool: queue

# Deploy group 2
- name: elasticsearch_data
  instances: 2
  networks:
  - name: default
    static_ips: (( static_ips(16, 17) ))
  resource_pool: elasticsearch_data
  persistent_disk_pool: elasticsearch_data

- name: kibana
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(8) ))
  resource_pool: kibana

- name: ingestor
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(1) ))
  resource_pool: ingestor

- name: ingestor-bosh-nats
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(4) ))
  resource_pool: ingestor

- name: parser
  instances: 1
  networks:
  - name: default
  resource_pool: parser

# Deploy group 3
- name: maintenance
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(6) ))
  resource_pool: maintenance

- name: ls-router
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(5) ))
  - name: elastic
    static_ips:
    -  VAR_ELK_IP # Specify an elastic IP for the router. Resources, proxied by the router, will be available through this IP. They include: kibana, elasticsearch, cluster_monitor, ingestor and syslog_server.
  resource_pool: haproxy

properties:
  nats_to_syslog:
    # Specify the NATS settings of the Bosh Director
    nats:
      user: VAR_NATS_USER  # Specify NATS user
      password: VAR_NATS_PASS  # Specify NATS password
      port: 4222  # Default value
      machines: [VAR_NATS_IP]  # Specify your NATS IPs

networks:
- name: default
  type: manual
  subnets:
  - range: VAR_CF1_NET_RANGE
    gateway: VAR_CF1_NET_GW
    cloud_properties:
      net_id: VAR_CF1_NET_ID  # Specify your network ID
      security_groups: [bosh]
    dns:
    - VAR_CF1_DNS_1
    - VAR_CF1_DNS_2
    reserved:
    - 192.168.1.2 - 192.168.1.95
    static:
    - 192.168.1.96 - 192.168.1.120

- name: elastic
  type: vip
  cloud_properties:
    security_groups:  # Specify your security groups used for 'elastic' network
    - bosh
    - logsearch
