meta:
  stemcell:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
    version: latest

releases:
- name: logsearch
  version: latest

name: logsearch
director_uuid: VAR_UUID # BOSH UUID

compilation:
  cloud_properties:
    zone: europe-west1-d

resource_pools:
- name: elasticsearch_master
  cloud_properties:
    zone: europe-west1-d
- name: elasticsearch_data
  cloud_properties:
    zone: europe-west1-d
- name: queue
  cloud_properties:
    zone: europe-west1-d
- name: ingestor
  cloud_properties:
    zone: europe-west1-d
- name: parser
  cloud_properties:
    zone: europe-west1-d
- name: kibana
  cloud_properties:
    zone: europe-west1-d
- name: maintenance
  cloud_properties:
    zone: europe-west1-d
- name: cluster_monitor
  cloud_properties:
    zone: europe-west1-d
- name: haproxy
  cloud_properties:
    zone: europe-west1-d
- name: errand
  cloud_properties:
    zone: europe-west1-d

jobs:
# Deploy group 1
- name: elasticsearch_master
  instances: 1

- name: cluster_monitor
  instances: 1

- name: queue
  instances: 1

- name: maintenance
  instances: 1

# Deploy group 2
- name: elasticsearch_data
  instances: 2

- name: kibana
  instances: 1

- name: ingestor
  instances: 1

- name: ingestor-bosh-nats
  instances: 1

- name: parser
  instances: 2

# Deploy group 3
- name: ls-router
  instances: 1
  cloud_properties:
    tags:
    - logsearch-router
  #networks:
  #- (( merge ))
  #- name: elastic
  #  static_ips:
  #  - MY-ELASTIC-IP # Specify an elastic IP for the router. Resources, proxied by the router, will be available through this IP. They include: kibana, elasticsearch, cluster_monitor, ingestor and syslog_server.

properties:
  nats_to_syslog:
    # Specify the NATS settings of the Bosh Director
    nats:
      user: VAR_NATS_USER  # Specify NATS user
      password: VAR_NATS_PASS  # Specify NATS password
      port: 4222  # Default value
      machines: [VAR_NATS_IP]  # Specify your NATS IPs

disk_pools:
- name: elasticsearch_master
  disk_size: 51200
- name: elasticsearch_data
  disk_size: 256000
- name: queue
  disk_size: 51200
- name: cluster_monitor
  disk_size: 51200

networks:
- name: default
  type: manual
  subnets:
  - range: VAR_CF1_NET_RANGE
    gateway: VAR_CF1_NET_GW 
    cloud_properties:
  #    zone: europe-west1-d
      network_name: cf
      subnetwork_name: logsearch 
      tags:
      - bosh-internal
      - logsearch-internal
    static:
    - 10.201.0.2 - 10.201.0.253
- name: elastic
  type: vip
  cloud_properties:
    security_groups:  # Specify your security groups used for 'elastic' network
    - bosh
    - logsearch
