releases:
- name: logsearch
  version: latest

name: logsearch
director_uuid: VAR_UUID # BOSH UUID


jobs:
# Deploy group 1
- name: elasticsearch_master
  instances: 1

- name: cluster_monitor
  instances: 1

- name: queue
  instances: 1

- name: maintenance
  instances: 1

# Deploy group 2
- name: elasticsearch_data
  instances: 2

- name: kibana
  instances: 1

- name: ingestor
  instances: 1

- name: parser
  instances: 2

# Deploy group 3
- name: ls-router
  instances: 1

properties:
  nats_to_syslog:
    # Specify the NATS settings of the Bosh Director
    nats:
      user: VAR_NATS_USER  # Specify NATS user
      password: VAR_NATS_PASS  # Specify NATS password
      port: 4222  # Default value
      machines: [VAR_NATS_IP]  # Specify your NATS IPs

networks:
- name: default
  type: manual
  subnets:
  - range: VAR_CF1_NET_RANGE
    gateway: VAR_CF1_NET_GW
    dns:
    - VAR_CF1_DNS_1
    - VAR_CF1_DNS_2
    reserved:
    - 192.168.1.2 - 192.168.1.95
    static:
    - 192.168.1.96 - 192.168.1.120
    cloud_properties:
      name: VAR_CF1_NET_NAME

