meta:
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

releases:
- name: logsearch
  version: latest

name: logsearch
director_uuid: VAR_UUID # BOSH UUID

jobs:
# Deploy group 1
- name: elasticsearch_master
  instances: 1

- name: cluster_monitor
  instances: 1

- name: queue
  instances: 1

- name: maintenance
  instances: 1

# Deploy group 2
- name: elasticsearch_data
  instances: 2

- name: kibana
  instances: 1

- name: ingestor
  instances: 1

- name: ingestor-bosh-nats
  instances: 1

- name: parser
  instances: 2

# Deploy group 3
- name: ls-router
  instances: 1
  networks:
  - (( merge ))
  - name: elastic
    static_ips:
    - VAR_ELK_IP  # Specify an elastic IP for the router. Resources, proxied by the router, will be available through this IP. They include: kibana, elasticsearch, cluster_monitor, ingestor and syslog_server.

properties:
  nats_to_syslog:
    # Specify the NATS settings of the Bosh Director
    nats:
      user: VAR_NATS_USER  # Specify NATS user
      password: VAR_NATS_PASS  # Specify NATS password
      port: 4222  # Default value
      machines: [VAR_NATS_IP]  # Specify your NATS IPs


disk_pools:
- name: elasticsearch_master
  disk_size: 102400
- name: elasticsearch_data
  disk_size: 512000
- name: queue
  disk_size: 102400
- name: cluster_monitor
  disk_size: 102400

networks:
- name: default
  type: manual
  subnets:
  - range: VAR_CF1_NET_RANGE
    gateway: VAR_CF1_NET_GW
    cloud_properties:
      subnet: VAR_CF1_SUBNET  # Specify your subnetwork ID
      security_groups: [bosh]
    dns:
    - VAR_CF1_DNS_1
    - VAR_CF1_DNS_2
    reserved:
    - 192.168.1.2 - 192.168.1.95
    static:
    - 192.168.1.96 - 192.168.1.120
- name: elastic
  type: vip
  cloud_properties:
    security_groups:  # Specify your security groups used for 'elastic' network
    - bosh
    - logsearch
