# --
# Default values + additional outputs.
# --
properties:
  logstash_ingestor:
    syslog:
      port: 5514
  logstash_parser:
    debug: true
    outputs: [ { plugin: "elasticsearch", options: {} }, { plugin: "mongodb", options: { uri: "192.168.1.1", database: "logsearch", collection: "logs" } }, { plugin: "syslog", options: { host: "127.0.0.1", port: 123} } ]
    elasticsearch:
      document_id: ~
      index: "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
      index_type: "%{@type}"
      data_hosts: [127.0.0.1]
