# --
# Default values + additional inputs.
# --
properties:
  logstash_ingestor:
    syslog:
      port: 5514
  logstash_parser:
    debug: false
    inputs: [ { plugin: "file", options: { path: "my/path/to/file" } }, { plugin: "syslog", options: { host: "127.0.0.1", port: 123} } ]
    outputs: [ { plugin: "elasticsearch", options: {} } ]
    elasticsearch:
      document_id: ~
      index: "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
      index_type: "%{@type}"
      data_hosts: [127.0.0.1]
