# --
# All "elasticsearch" properties are set with non-null values.
# --
properties:
  logstash_ingestor:
    syslog:
      port: 5514
  logstash_parser:
    debug: false
    outputs: [ { plugin: "elasticsearch", options: {} } ]
    elasticsearch:
      document_id: "abc"
      index: "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
      index_type: "%{@type}"
      routing: "%{some_field}"
      idle_flush_time: 100
      data_hosts: [127.0.0.1]
