# --
# Only required "elasticsearch" properties are set.
# --
properties:
  logstash_ingestor:
    syslog:
      port: 5514
  logstash_parser:
    debug: false
    outputs: [ { plugin: "elasticsearch", options: {} } ]
    elasticsearch:
      index: "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
      index_type: "%{@type}"
      data_hosts: [127.0.0.1]
