# frozen_string_literal: true
source "https://rubygems.org"

gem 'rspec'
gem 'bosh-template'
gem 'rake'

# Versions matching logsearch release v5.0.0
gem 'logstash-core', '5.5.0', require: true
gem 'logstash-filter-mutate', '3.1.3'
gem 'logstash-filter-grok', '3.2.3'
gem 'logstash-filter-syslog_pri', '3.0.2'
gem 'logstash-filter-date', '3.0.3'
gem 'logstash-filter-kv', '3.1.1'
gem 'logstash-filter-json', '3.0.2'
gem 'logstash-filter-ruby', '3.0.2'
gem 'logstash-filter-drop', '3.0.2'
gem 'logstash-filter-translate'
gem 'logstash-input-redis', '3.1.1'
gem 'logstash-output-elasticsearch', '5.2.0'
gem 'logstash-output-stdout', '3.1.0'
gem 'logstash-output-syslog'
gem 'logstash-output-mongodb'
gem 'logstash-codec-plain', '3.0.2'
gem 'logstash-input-tcp'
gem 'logstash-input-udp'
gem 'logstash-input-file', '4.0.0'
gem 'logstash-input-syslog', '3.1.1'

gem 'logstash-filter-translate'
